### PR TITLE
fix eventbrite for new structure

### PR DESCRIPTION
**Pull request by erfanio**
~because of the change in [this line](https://github.com/unihackhq/skilled-acolyte-backend/pull/30/files#diff-00345c6c9814546c14034c61183a28b8R31) you need to create a student first then a user (because `belongTo` stores the association in `Student` but `hasOne` stores it in `User` [docs](http://docs.sequelizejs.com/manual/tutorial/associations.html#difference-between-hasone-and-belongsto))~

~Sequelize has a thing for creating associated models together, but because the UUIDs have to be the same I'm creating them in javascript and giving it to sequelize (I'm sure sequelize does kinda the same thing behind the scene)~

Fix schema and make eventbrite prepopulate into the same structure as other endpoints

Also add user to the createStudent's response
the response will be something like

```
{
	"id": "a428cbe8-1345-4dc7-9673-a4a7c0b5f690",
	"university": "ff0e40cd-84f0-445b-a21a-0f62a3ed1594",
	"studyLevel": "First Year",
	"degree": "Unknown",
	"dietaryReq": "No",
	"medicalReq": "No",
	"shirtSize": "M",
	"photoUrl": "http://example.com",
	"updatedAt": "2017-08-02T15:26:41.035Z",
	"createdAt": "2017-08-02T15:26:41.035Z",
	"user": {
		"deactivated": false,
		"firstName": "Some",
		"lastName": "Dude",
		"preferredName": "Some",
		"email": "me@example.com",
		"dateOfBirth": "1990-01-01T00:00:00.000Z",
		"gender": "male",
		"mobile": "40000000",
		"id": "a428cbe8-1345-4dc7-9673-a4a7c0b5f690",
		"updatedAt": "2017-08-02T15:26:41.044Z",
		"createdAt": "2017-08-02T15:26:41.044Z",
		"authType": null,
		"authId": null,
		"accessToken": null
	}
}
```

### CODE REVIEW

**Comment by erfanio** [comment]
@terencehuynh if you want merge if it's good, it will show up in your pull request

**Comment by erfanio** [comment]
I figured out a way simpler way of creating students

**Comment by terencehuynh** [comment]
Student has a dependency on User, so I would argue User needs to be created first - no?

**Comment by hugomd** [comment]
@terencehuynh Is it a dependency or an association though?

**Comment by terencehuynh** [comment]
@hugomd Technically Association. In the `models/index.js` class:

```
db.Student.hasOne(db.User, {
  foreignKey: 'id',
  targetKey: 'id',
  as: 'user'
});
```

It's basically a way to emulate this:
https://www.postgresql.org/docs/9.1/static/tutorial-inheritance.html

Makes things easier to extend for the future: since not all users are student, but students are going to be users.

**Comment by hugomd** [comment]
Yup, I see — I suppose this indicates that a user must be created
first, then!

--
Hugo Müller-Downing
http://hu.md/


On Thu, Aug 3, 2017, at 15:01, Terence Huynh wrote:
> @hugomd[1] Technically Association. In the models/index.js class:


> db.Student.hasOne(db.User, { foreignKey: 'id', targetKey: 'id', as:
> 'user' });
>> It's basically a way to emulate this:
> https://www.postgresql.org/docs/9.1/static/tutorial-inheritance.html> Makes things easier to extend for the future: since not all users are
> student, but students are going to be users.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/hugomd
  2. https://github.com/unihackhq/skilled-acolyte-backend/pull/31#issuecomment-319868249

**Comment by erfanio** [comment]
I fixed eventbrite too
@terencehuynh @hugomd review pls

**Comment by erfanio** [comment]
@terencehuynh so in the previous model structure `Student` had a dependency on `User` but when you changed `belongTo` to `hasOne` the dependency switched, and now `User` has a dependency on `Student`.
So if we try to create a user first we'll get `insert or update on table "Users" violates foreign key constraint "Users_id_fkey"`

**Comment by terencehuynh** [comment]
Ah. Okay, it should be a `belongTo` then. Whoops sorry @erfanio.

**Comment by erfanio** [comment]
@terencehuynh lol!!!!! I thought you changed it for a reason 😑

**Comment by erfanio** [comment]
@terencehuynh okay all done now

**Comment by erfanio** [comment]
re e9b6ffb
idk why the casing is so random....
I get 
```
{
	"id": "7a244d52-c544-4737-bb37-d01e82baa0de",
	"name": "some team",
	"description": " ",
	"photoUrl": "http://example.com",
	"EventId": "92676d3c-0c93-46f8-b11d-972812ffa071",
	"updatedAt": "2017-08-04T16:31:51.701Z",
	"createdAt": "2017-08-04T16:31:51.701Z"
}
```

**Comment by erfanio** [comment]
An endpoint to join a team/accept invite was missing.. i added it

**Pull request merged**
