### PR TITLE
change team creation

### PR DESCRIPTION
**Pull request by erfanio**
Team creation was weird before
Now two different endpoints for when student should be added and when they should not.

### CODE REVIEW

**Comment by hugomd** [comment]
@erfanio I kind of feel that it made sense before... You create a team and are therefore added to that team..?

**Comment by erfanio** [comment]
Two things made me uncomfortable about tye previous way.  
The payload was aletering behaviour a lot.   
The id was being extracted from the jwt.

The id in jwt made it more difficult for admins to create a team and add a person to it.

Also the old way we had to make sure admins don't use `addMe: true` cause they aren't guaranteed to have a usedId in their jwt

**Comment by hugomd** [comment]
@erfanio `addMe` defaults to `false` though, and if there's a UI for it then admins will never be added to the team?

I don't think there's anything wrong with altering behaviour based on the payload, if the behaviour is simple enough. I'd argue that offloading logic to the server makes sense, especially if it makes the client less complex.

Also, any user who's logged in, and has a valid JWT should be _guaranteed_ to have a `userId` in their JWT.

**Comment by erfanio** [comment]
@hugomd for admins it's the difference between three api calls to make a team for a student with the old behaviour (make team, invite, accept) and one in the new behaviour.

Even if there is a userId in admin's jwt, it still wouldn't be a student's userId.

**Comment by erfanio** [comment]
@hugomd Tell me what you think.

What if we look at the jwt type and if it's a student we add them to the team. Otherwise we just create the team.

**Comment by hugomd** [comment]
@erfanio But it shouldn't matter — the difference is negligible, a student is still a user. 

Re your last comment, I think that makes the most sense ✅

**Comment by erfanio** [comment]
@hugomd The problem with user not being student is that they can't be added to a team (cause team needs a student for association)

Alright I'll close this one, make a new one

**Pull request closed without merging**
